services:
  postgres:
    container_name: postgresql-order
    image: postgres:17.4
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: order
      POSTGRES_PASSWORD: order
      POSTGRES_DB: order

volumes:
  postgres-data:

