server:
  port: 8084

spring:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:10000
    producer:
      bootstrap-servers: localhost:10000


servers:
  store:
    url: http://localhost:8081/api/store/
  product:
    url: http://localhost:8082/api/product/
  cart:
    url: http://localhost:8083/api/cart/


