server:
  port: 8084

spring:

  datasource:
    url: jdbc:postgresql://localhost:5433/order
    username: order
    password: order
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:10000
    producer:
      bootstrap-servers: localhost:10000


servers:
  store:
    url: http://localhost:8081/api
  product:
    url: http://localhost:8082/api
  cart:
    url: http://localhost:8083/api


